version: "3.8"

services:

  user-service:
    container_name: user-service
    build:
      context: "./user-service"
      dockerfile: Dockerfile
    image: "arnoldtanu-user-service:1.0.0"
    environment:
      PORT: 3000
      TZ: UTC
      MONGODB_URL: mongodb://root:example@mongo:27017/
      COLLECTION_NAME: user
      API_KEY: 80MnVkyQRPXGMkpZUhEp2p3JShR9XhVJ
      AMQP_URL: amqp://rabbitmq
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./user-service/src
        target: /app/src
    restart: on-failure
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo:7.0.5
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3.11.28-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    restart: on-failure